### PR TITLE
About the ASP.NET Community Standup

### PR DESCRIPTION
**Pull request by hishamco**
Based on issue #10 I made this PR, I hope you like it @DamianEdwards :smile:

### CODE REVIEW

**Comment by DamianEdwards** [comment]
There's quite a bit more content in this than I had in mind. Certainly the links to LinkedIn profiles is definitely not what we're going for. Just a simple paragraph that describes what the show is and mention the hosts by name, linked to their Twitter profiles will suffice.

**Comment by hishamco** [comment]
I was wondering about the LinkedIn before I push the PR, I will remove the Urls and I will use the twitter link in proper way

**Comment by hishamco** [comment]
Here is the screenshot
capture

**Comment by hishamco** [comment]
i update the PR, @DamianEdwards hope it is better

**Comment by IanCollinson** [comment]
Given this weeks episode it might be wise to drop the 30 mins part!

**Comment by hishamco** [comment]
@DamianEdwards is this enough for now?

**Comment by hishamco** [comment]
What's the status of this PR?!!

**Comment by hishamco** [comment]
@DamianEdwards any idea how we can end up with this?

**Comment by hishamco** [comment]
@DamianEdwards I updated this PR little bit, are you still interest on it?

**Pull request closed without merging**
