### PR TITLE
Simplify IShowService

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
@DamianEdwards your feedback

**Comment by hishamco** [comment]
@DamianEdwards is this fine for you?

**Comment by DamianEdwards** [comment]
No, I don't like using `IHttpContextAccessor`.

**Comment by hishamco** [comment]
Strange!! Is there any reason to avoid using ```IHttpContextAccessor```?

**Comment by DamianEdwards** [comment]
The service doesn't depend on `IHttpContext`, it just needs the user.

**Comment by hishamco** [comment]
I injected the ```IHttpContextAccessor``` to access the ```User```, which is similar to what you did here https://github.com/aspnet/live.asp.net/blob/92d0385e7d1e4e052deba4bbaaf13bacbf9d2d7e/src/live.asp.net/Controllers/HomeController.cs#L27, furthermore I'm not sure why it depends on the ```ClaimsPrincipals``` while the intend is to get the recorded shows

**Comment by DamianEdwards** [comment]
In the example you gave, I grabbed the user from the class I'm already in, so that's not the same. I need the user because I don't allow non-authenticated to bypass the cache.

**Comment by hishamco** [comment]
It uses ```ControllerBase.User``` https://github.com/aspnet/Mvc/blob/1dd1d49321eab65431e9c4b0465d7d9f2b23dbdf/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs#L230, which is the similar thing that I access it via DI

**Comment by DamianEdwards** [comment]
It really isn't :smile:

**Comment by hishamco** [comment]
I got confused 😄

**Pull request closed without merging**
