### PR TITLE
Add semantic importance and meaning to show badges/labels

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commits adds HTML5 semantics to show StandBy/OnAir badges.
They will be now differently rendered or spoken - as intended by visual
clues.

There is no visual change in how visual clues are rendered by BS CSS, as `strong` tag has the same weight in BS css as `label` class. The change will be seen in other readers or heard in readers:

Thanks!

### CODE REVIEW

**Comment by hishamco** [comment]
Looks good :smile:

**Comment by DamianEdwards** [comment]
That looks bolder to my eye without actually checking it yet. I'll try it and check for myself in a few browsers before merging.

**Comment by hishamco** [comment]
You are right @DamianEdwards it's bolder, needs some UI improvements

**Comment by peterblazejewicz** [comment]
Guys, I do know what I'm doing:
https://github.com/twbs/bootstrap/blob/master/less/labels.less#L9
https://github.com/twbs/bootstrap/blob/master/less/normalize.less#L120


Unless you're using local stylesheet you should always get normalized bold weight.
Thanks!

**Comment by hishamco** [comment]
@peterblazejewicz I know what you did. Seems the font is bolder, perhaps @DamianEdwards doesn't notice that before in **ON AIR**, but it's obvious in **STANDBY**

**Comment by DamianEdwards** [comment]
OK I think I know what's happening here. @peterblazejewicz  is doing this work on a Mac and thus he's seeing different fonts to us. Am I correct? The font we use on Windows (Segoe UI Light) has very mild bolding, so your screenshots (which use Helvetica I'm guessing) make the bold look much more pronounced.

**Comment by peterblazejewicz** [comment]
@DamianEdwards Yes, I'm working exclusively on Mac for ASP.NET 5 :D  Thanks folks!

**Pull request merged**
