### PR TITLE
Added a calendar notification 10 minutes before the standup begins

### PR DESCRIPTION
**Pull request by khellang**

### CODE REVIEW

**Comment by DamianEdwards** [comment]
This seems to have some issues. I tried it now in [staging](https://ms-asp-standup-staging.azurewebsites.net/) and when I open the downloaded ICS in Outlook it sets the reminder to 306 days.

**Comment by khellang** [comment]
Hmm. It worked perfectly for me here. This is imported from staging:

image

Maybe it's an Outlook-specific thing?

**Comment by DamianEdwards** [comment]
I've deployed a change to staging, can you confirm that it still works for you?

**Comment by khellang** [comment]
Hmm. The older RFC ([2445](https://tools.ietf.org/html/rfc2445#section-4.8.6.3)) says

> Example: A trigger set 15 minutes prior to the start of the event or to-do.
> ```
> TRIGGER:-P15M
> ```

But the newer RFC ([5545](https://tools.ietf.org/html/rfc5545#section-3.8.6.3)) says

> Example:  A trigger set 15 minutes prior to the start of the event or to-do.
> ```
> TRIGGER:-PT15M
> ```

See the extra `T` there? That might have something to do with it.

While you're in there changing stuff, you might also want to look at some of the newer properties ([RFC 7986](https://tools.ietf.org/html/rfc7986)) to the iCal format, like URL, etc.

**Comment by alexwiese** [comment]
306 days is ~10 _months_ not minutes. I think it should have a preceding `T` to specify time duration  not date. Eg. `-PT10M`

**Comment by khellang** [comment]
Looks like it's now 15 minutes *after* start:

image

**Comment by DamianEdwards** [comment]
Doh, let me add the minus sign back

**Comment by DamianEdwards** [comment]
Try again?

**Comment by khellang** [comment]
Works now 👍

**Comment by DamianEdwards** [comment]
Awesome, thanks

**Pull request merged**
