### PR TITLE
Open the video in a new tab

### PR DESCRIPTION
**Pull request by hishamco**
From UI & Navigation perspective it will be nice to open the video link in another tab without leaving `live.asp.net` landing page

### CODE REVIEW

**Comment by Eilon** [comment]
My personal view is that the user should be in control of their browser and not force anything to open in a new tab/window. If someone wants to open a link in a new tab/window the browser has multiple facilities to do this.

**Comment by TimMurphy** [comment]
+1 Eilon

Probably the **only** time a website should open new window or tab is a help page for a form so the user does not lose any data they have already entered.

**Comment by hishamco** [comment]
Perhaps :smile:

**Comment by JimiC** [comment]
+1 Eilon

**Comment by DamianEdwards** [comment]
Yeah I agree with Eilon, users can middle-click or ctrl-click to get that behavior if they wish.

**Pull request closed without merging**
