### PR TITLE
Use nameof for view names in the controllers and remove some whitespace.

### PR DESCRIPTION
**Pull request by wforney**
A couple of minor things... Was wondering if using nameof() like this should be a standard thing now?

### CODE REVIEW

**Comment by hishamco** [comment]
It will be nice to separate them into two commits specially if there's extra white spaces in other files

**Comment by DamianEdwards** [comment]
@wforney would you mind rebasing this please?

**Comment by wforney** [comment]
@DamianEdwards sure, I'll take a look at it when I have some time. Probably toward end of week/weekend.

**Comment by hishamco** [comment]
:watch:

**Pull request closed without merging**
