### PR TITLE
React to remove GC trigger for cache eviction 

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
I think we should remove the `CompactOnMemoryPressure` from `AddCachedWebRoot`, after the commit https://github.com/aspnet/Caching/commit/f44517ef0eb6ca7833dbdc7f3aa3cb3832c434be

/cc @JunTaoLuo @DamianEdwards

**Comment by JunTaoLuo** [comment]
This isn't currently needed since the repo uses FTS (1.1) dependencies. Once it updates to 2.0 packages, we'll need to react to more than just this breaking change.

**Comment by hishamco** [comment]
@DamianEdwards can we upgrade to `1.2.0-*` if it's possible, because I'm working on other hand to use our new `TagHelperComponent` to simplify some scenarios in the current code

I'm not sure if the upgrade will help to fix this issue too

**Comment by DamianEdwards** [comment]
Like I said in other PR, I don't update this site until an official preview release.

**Pull request closed without merging**
