### PR TITLE
Show details page with description, TOC and time parameter

### PR DESCRIPTION
**Pull request by eloekset**
This is an early PR for a show details page with an embedded YouTube player that supports jumping to specific points in the video from a Table of Contents list below. It also supports time parameter in the URL, making it easy to link to a specific point in the video.

I've made two implementations of the IShowDetailsService for FileSystem and AzureStorage.

So far I've only added real content in a static file for the first video in the DesignData.Shows list, just to have some real data to test the functionality and get a feel of how it works.

I think it's a good idea to have fairly detailed text description of each show, to have it indexed by search engines. **I often want to go back to these live.asp.net videos, when I think of something that I know I've heard and seen. But without an index it's very difficult to find the right video and the right position to the specific content that I think of.**

If you feel it's too much work to write a description and TOC for each video, I can make an implementation for a SQL backend together with an edit page that the community can sign up to, so we all can participate in writing the meta data for each show.

Here are some screenshots of the current implementation of it:
screenshot1
Image 1 - The URL to a specific show is /Home/Show?showId=<YouTubeId>

screenshot2
Image 2 - When the user clicks a position link within the show, a query parameter t=<hours>h<minutes>m<seconds>s is added to the URL, and it pushes to the browser back stack.

screenshot3
Image 3 - The page also supports navigation to a specific position within a show from the URL.

screenshot4
Image 4 - The current structure of the document for show details.

### CODE REVIEW

**Comment by eloekset** [comment]
This can be an alternative if you want to allow the community to edit show detail contents: https://github.com/eloekset/UnofficialLiveAspNetShowDetailsTestRepo

As the description of that repo says, that alternative is not (yet) part of this pull request, as the work to enable it is done in a separate branch.

**Comment by hishamco** [comment]
@eloekset I appreciate your efforts, the idea is cool, but it needs a dedicated content writer, AFAIK @csharpfritz is the one who summarize the weekly standup.
Allowing everyone to contribute is makes me wonder (no moderation), I'm not sure if Jeff can add the time for everything is happen in the stand up, because it's little bit hard.
If the idea is acceptable by all, is that means we need to archive all the previous episodes and edit the previous blog posts again or start from where we are now

**Comment by csharpfritz** [comment]
It takes me a minimum of 2-2.5x the duration of the standup to document all of the shared links and write up summaries of what was discussed with appropriate links to the pages or code they have referenced.  I also drop in screenshots or code snippets every now and again as appropriate.

Adding time codes to the weekly summary post would make the authoring of that document much longer.

**Comment by eloekset** [comment]
I wasn't aware of that blog, @csharpfritz. The posts are very descriptive, so I think the show details page can use this link https://blogs.msdn.microsoft.com/webdev/tag/communitystandup/ to grab the contents of the blog posts, match them to the show date and display the content directly under the embedded video player. Does that sound like a good idea? I can test it out in a separate branch.

I think it's possible since all posts seem to have the show date as part of the link: https://blogs.msdn.microsoft.com/webdev/2015/09/22/asp-net-community-standup-september-15-2015/. I'll just have to parse the part after **asp-net-community-standup** as a date, and see if it matches the show date.

The video index can still be a contribution by the community, if enough people are interested. The GitHub repo approach, that I mentioned yesterday, would have moderation by design. If the **aspnet** GitHub user creates a new repo called **live.asp.net-content**, the user(s) with write access (probably @csharpfritz and maybe a few others) would have to merge pull requests from the community and decide whether the contributions should be merged or not. That shouldn't take to much time, if not the community goes wild and opens a huge amount of pull requests. ☺

**Comment by eloekset** [comment]
I've now created a branch to test grabbing content from the matching blog post. It's difficult to make it look perfect, since I have to extract parts of the HTML content, but it works. If I merge this with the other branches, it can work as a fallback when there's no description provided manually in a file in AzureStorage or GitHub content repo. The result can be tested by checking out this branch: https://github.com/eloekset/live.asp.net/tree/showDetailsPage_ContentFromBlog

Here are some screenshots of three test shows where the content is grabbed from the blog. (I've zoomed out a lot before taking the screenshots.)

screenshot5
screenshot6
screenshot7

I've added a backlink to the original blog post from which the content is grabbed:
backlink

**Pull request closed without merging**
