### PR TITLE
Remove unused client dependencies. Closes #36

### LINKED ISSUE #36: Remove unused client side dependencies
The client-side dependencies from initial project bootstrap can be removed:
https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/bower.json#L6-L7

```
"bootstrap-touch-carousel": "0.8.0",
 "hammer.js": "2.0.4"
```

They are not used. The website CSS stylesheet will require removal of `bootstrap-touch-carousel` related code as well.

If removed, it will simplify and clarify client-side dependencies in project.

Is it OK to PR this?

Thanks!

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit is a complementary commit to 9ea1e135 as it removes references to client-side dependencies that are already not used by the implementation:
- update Bower.json configuration file
- update site stylesheet

Thanks!

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
I"ve already signed CLA, DocuSign hash: 0E50AB6553AB4EA09BFB440EF34709F61

**Comment by Eilon** [comment]
@peterblazejewicz are you sure it's the .NET Foundation CLA? If so I can have someone investigate.

(BTW we used to use an MS Open Tech CLA, but changed a few months ago.)

**Comment by peterblazejewicz** [comment]
@Eilon Thanks! That was it obviously :dancer:

**Comment by Eilon** [comment]
@peterblazejewicz thanks :smile:

**Pull request merged**
