### PR TITLE
Format project.json

### PR DESCRIPTION
**Pull request by hishamco**
This include remove extra whitespace and organize the packages

### CODE REVIEW

**Comment by DamianEdwards** [comment]
I actually like the extra line breaks to denote the logical sections of the file. Happy to accept the sorting of packages if you fix that.

**Comment by hishamco** [comment]
@DamianEdwards IMHO the line breaks in `project.json` is not needed, it's very need in the code to denote the logical sections as you mentioned before, and that is what I have seen in all asp.net repos, specially the **Localization** one becuase I like it :smile:

**Comment by TimMurphy** [comment]
+1 for extra line breaks.

**Comment by hishamco** [comment]
@TimMurphy if is that why we don't have line break after each section?? and why we didn't see such thing in `config.json`?!!

**Comment by JimiC** [comment]
Either put extra line breaks in all sections or remove all of them. Keep consistency throughout the file.

**Comment by hishamco** [comment]
That is what I mean @JimiC

**Comment by TimMurphy** [comment]
I agree it should be consistent within a file but not necessarily all files. config.json is tiny so whitespace is not as important.

**Comment by hishamco** [comment]
@DamianEdwards PR has been updated

**Comment by Eilon** [comment]
Folks, please, I'm pretty sure @DamianEdwards gets to decide how the project.json files in the project should look.

**Comment by TimMurphy** [comment]
:thumbsup: @Eilon

**Comment by hishamco** [comment]
Yep @Eilon, the doubt above about the consistency nothing else :smile:

**Pull request closed without merging**
